services:
  markdown_badges_site:
    container_name: markdown_badges_site
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - main_sites

networks:
  main_sites:
    external: true
